preload = /home/fnnfox/Pictures/wallpaper_night.png

wallpaper {
	monitor = HDMI-A-1
	path = /home/fnnfox/Pictures/wallpaper_night.png
}

wallpaper {
	monitor = DP-2
	path = /home/fnnfox/Pictures/wallpaper_night.png
}

splash = false
ipc = on
