preload = /home/fnnfox/Pictures/Heaven Pierce Her - ULTRAKILL- VIOLENCE - 7-4 wallpaper.jpg

wallpaper = HDMI-A-1,/home/fnnfox/Pictures/Heaven Pierce Her - ULTRAKILL- VIOLENCE - 7-4 wallpaper.jpg

splash = false
ipc = on
