$font = MxPlus IBM VGA 8x16
$monitor = HDMI-A-1
$bgcolor = 000000

general {
	hide_cursor = true
}

animations {
	enabled = false
}

background {
	monitor = $monitor
	color = rgb($bgcolor)
}

label {
	monitor = $monitor
	text = <span foreground='##$bgcolor' background='##aaaaaa'> Linux </span>
	font_family = $font
	font_size = 22
	position = 0, 160
	halign = center
	valign = center
}

label {
	monitor = $monitor
	text = <span>\
	A lock has occurred. To continue:<br/><br/>\
	Insert user password to return to Linux, or<br/><br/>\
	Press CTRL+ALT+F1-12 to enter another TTY. If you do this,<br/>\
	you will NOT lose any unsaved information in all open applications,<br/>\
	until you reboot your computer.<br/><br/>\
	Context: $TIME, $USER, $LAYOUT\
	</span>
	font_size = 22
	font_family = $font
	position = 300, -30
	halign = left
	valign = center
}

input-field {
	monitor = $monitor
	size = 600, 90
	rounding = 0
	dots_text_format = *
	outline_thickness = 0
	inner_color = rgb($bgcolor)

	font_family = $font
	font_color = rgb(ffffff)
	check_color = rgb(ffffff)
	fail_color = rgb(ff0000)
	swap_font_color = true
	fade_on_empty = false
	placeholder_text = Insert password to continue _
	check_text = Please wait...
	fail_text = $FAIL ($ATTEMPTS)
	position = 0, -220
	halign = center
	valign = center
}

