general {
	lock_cmd = pidof hyprlock || hyprlock       # Команда блокировки
	before_sleep_cmd = loginctl lock-session    # Лочить перед сном (закрытием крышки)
	after_sleep_cmd = hyprctl dispatch dpms on  # Включать экран при пробуждении
}

listener {
	timeout = 300                                # 5 минут простоя
	on-timeout = loginctl lock-session           # Заблокировать экран
}

listener {
	timeout = 600                                # 10 минут простоя
	on-timeout = hyprctl dispatch dpms off       # Выключить монитор
	on-resume = hyprctl dispatch dpms on         # Включить обратно
}
