# Мониторы
monitor = HDMI-A-1, 1920x1080@60, 0x0, 1
monitor = DVI-D-1, 1280x1024@75, 1920x0, 1

# Переменные окружения
env = XCURSOR_THEME, Tela-dark
env = XCURSOR_SIZE, 24
env = HYPRCURSOR_THEME, Tela-dark # Новый формат курсоров в Hyprland
env = HYPRCURSOR_SIZE, 24

# Форсируем Wayland для Firefox и приложений
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland

# Темизация Qt (чтобы Dolphin был красивым)
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1

# --- АВТОЗАПУСК ---
# Важнейшая часть для openSUSE (ввод пароля root)
exec-once = /usr/libexec/polkit-kde-authentication-agent-1
exec-once = flatpak run com.github.wwmm.easyeffects --gapplication-service

# Красиво?
exec-once = hyprpaper
exec-once = waybar
exec-once = dunst
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Клавиши
bind = SUPER, Return, exec, kitty
bind = SUPER, Q, killactive,
bind = SUPER, M, exit,
bind = SUPER, R, exec, hyprctl reload
bind = SUPER, D, exec, rofi -show drun

bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d

bind = SUPER SHIFT, left, movewindow, l
bind = SUPER SHIFT, right, movewindow, r
bind = SUPER SHIFT, up, movewindow, u
bind = SUPER SHIFT, down, movewindow, d


# Перемещение по рабочим столам
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5

# Плавающее окно
bind = SUPER SHIFT, T, togglefloating
bind = SUPER SHIFT, F, fullscreen

bindm = SUPER, mouse:272, movewindow
bindm = SUPER SHIFT, mouse:272, resizewindow

# Курсор
input {
	kb_layout = us,ru
	kb_options = grp:alt_shift_toggle
	follow_mouse = 2
}

device {
	name = logitech-g502-hero-gaming-mouse
	accel_profile = flat
	sensitivity = -0.35
}

general {
	gaps_in = 4
	gaps_out = 6
	border_size = 2
	col.active_border = rgb(ffb86c)
	col.inactive_border = rgba(00000088)
}

decoration {
	rounding = 3
}

animations {
	enabled = true
	bezier = ease, 0.4, 0.02, 0.21, 1
	animation = windows, 1, 3, ease
}
