# --- ОБЩИЕ НАСТРОЙКИ ---
general {
	no_fade_in = false
	grace = 0
	disable_loading_bar = true
}

# --- ФОН (ОБОИ) ---
background {
	monitor =
	# Либо укажи путь к картинке: path = /home/fnnfox/Wallpapers/lock.png
	# Либо используй скриншот текущего состояния:
	path = screenshot
	
	# Эффект размытия (Blur)
	blur_passes = 3 # 0 - выкл, 3 - сильно размыто
	blur_size = 7
	noise = 0.0117
	contrast = 0.8916
	brightness = 0.8172
	vibrancy = 0.1696
	vibrancy_darkness = 0.0
}

# --- ПОЛЕ ВВОДА ПАРОЛЯ ---
input-field {
	monitor = HDMI-A-1
	size = 250, 50
	outline_thickness = 3
	dots_size = 0.2 # Размер точек пароля
	dots_spacing = 0.64 # Расстояние между точками
	dots_center = true
	outer_color = rgba(50, 50, 60, 0.9) # Цвет рамки
	inner_color = rgba(30, 30, 46, 0.8) # Цвет поля
	font_color = rgb(205, 214, 244)
	fade_on_empty = true
	placeholder_text = Password... # Текст подсказки
	hide_input = false
	position = 0, -100 # Сдвиг вниз от центра
	halign = center
	valign = center
}

# --- РАСКЛАДКА КЛАВИАТУРЫ ---
label {
	monitor = HDMI-A-1
	# $LAYOUT покажет что-то вроде "English (US)" или "Russian"
	text = $LAYOUT
	color = rgb(205, 214, 244)
	font_size = 14
	font_family = JetBrains Mono Nerd Font

	# Позиция: чуть ниже поля ввода (координаты зависят от твоего экрана)
	# Если input-field имеет position 0, -60, то тут ставим ниже
	position = -10, 10

	halign = right
	valign = bottom
}

# --- ЧАСЫ (БОЛЬШИЕ) ---
label {
	monitor = HDMI-A-1
	text = cmd[update:1000] echo "<b>$(date +"%H:%M")</b>"
	color = rgb(205, 214, 244)
	font_size = 64
	font_family = JetBrains Mono Nerd Font 10
	position = 0, 80 # Сдвиг вверх
	halign = center
	valign = center
	shadow_passes = 2
}

# --- ДАТА (ПОД ЧАСАМИ) ---
label {
	monitor = HDMI-A-1
	text = cmd[update:18000000] echo "<b>$(date +'%A, %d %B %Y')</b>"
	color = rgb(205, 214, 244)
	font_size = 18
	font_family = JetBrains Mono Nerd Font
	position = 0, 20
	halign = center
	valign = center
}

# --- ПРИВЕТСТВИЕ ---
label {
	monitor = HDMI-A-1
	text = Hi there, $USER
	color = rgba(200, 200, 200, 1.0)
	font_size = 14
	font_family = JetBrains Mono Nerd Font
	position = 0, -30
	halign = center
	valign = center
}
